---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres16
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4-45
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "400"
      shared_buffers: 256MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    requests:
      cpu: 250m
      memory: 200Mi
    limits:
      memory: 1Gi
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 7d
    barmanObjectStore: &barmanObjectStore
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      # https://cloudnative-pg.io/documentation/1.19/backup_recovery/#other-s3-compatible-object-storages-providers
      destinationPath: s3://pg-backup/
      endpointURL: https://192.168.8.129:9002
      # Note: serverName version needs to be implemented
      # when recovering from an existing cnpg cluster
      serverName: &currentCluster main-postgres16-v1
      s3Credentials:
        accessKeyId:
          name: &minioSecret cloudnative-pg-cluster-secret
          key: aws_access_key_id
        secretAccessKey:
          name: *minioSecret
          key: aws_secret_access_key
  bootstrap:
    recovery:
      source: &previousCluster main-postgres16-v1
  externalClusters:
    - name: *previousCluster
      barmanObjectStore:
        <<: *barmanObjectStore
        serverName: *previousCluster
