---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1ttpdjs0hthl58l4sc4n4dufuchumvlpj7zra0w48mpccf96ax3mqtap3ae"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1ttpdjs0hthl58l4sc4n4dufuchumvlpj7zra0w48mpccf96ax3mqtap3ae"
stores:
  yaml:
    indent: 2
