# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: gatus-secret
stringData:
    PUSHOVER_TOKEN: ax8qe3wv42j57f3yhq54kryo6wz986
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
