---
# databases/cloudnative-pg/operator/externalsecret.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
    labels:
        cnpg.io/reload: "true"
stringData:
    password: postgres
    username: postgres
    AWS_ACCESS_KEY_ID: 2VNAHAbZEtSVCXFSMsOf
    AWS_SECRET_ACCESS_KEY: spKTEAivwgZAeV1pzuqFUOrL2st7rSEg7Tqc00SI
