# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:3f74l8wMkMDaKva7Ap5CuHFaeraO5qeqqwXAWOLLWIXDbjnz9I+tAw==,iv:UK+dHikbEKpwMn1k31pOP569+JgsBjg63fuYz/bRWwg=,tag:QeE+6NpxmkqKjmmwYWR3hA==,type:str]
sops:
  age:
    - recipient: age1ttpdjs0hthl58l4sc4n4dufuchumvlpj7zra0w48mpccf96ax3mqtap3ae
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVW5WVU9LaHl3bEI3OUpt
        RHlaWG56b1I2Nlpwd1FJekRzY3RiYU4xUGhzCjlvK2RqdFNZanAvZTZwc3BhcGI0
        dHprRy9yNU1DcDNlMnJBamRvS25lcjgKLS0tIEh1NE53Q2NSZ1VFWnRjekpXQjdw
        MjM2Q0ZmdDYvMWM1NkJpQXN0d2JFeEEK8aMI+3fXizGqsX20KQii685AJ42gpoYu
        wS328riGpv5YuQqnz3Co8N/5joDnFWcow46LOyHpAWQm18v+BnLEyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-13T03:00:58Z"
  mac: ENC[AES256_GCM,data:SFE2Muv6AwACNeDMnTYq9ZUws8KSIwi2BWbQKdMhZ4DJw4dogGTbnik8DUyyZx7LH7U6d3UsC8q8rIIxaGPihZ/oTdO5/asvB8oGsjhuc9y4ZwF4Xq8UhLzh26KZiD9mjLl0bijRJ/0lKFYn3FTinEA8ukVgoLuXzRh8Rx/rRIU=,iv:jBhuNtzLLPGkhrfKLTl3zjIqArAdyP5KgyRjI+XSgtQ=,tag:cFFVd7r8G9Ow4zxwzn8dag==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
