---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard
spec:
  secretName: tls-adguard
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: dns.${SECRET_DOMAIN}
  dnsNames:
    - external.samcloud.online
    - adguard.samcloud.online
  privateKey:
    rotationPolicy: Always
