---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: network
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      adguard:
        replicas: 1
        strategy: RollingUpdate

        containers:
          app:
            image:
              repository: adguard/adguardhome
              tag: v0.107.61
            env:
              TZ: UTC
              ADGUARD_DATA_DIR: &datadir /opt/adguardhome/data
              ADGUARD_CONF_DIR: &confdir /opt/adguardhome/conf


    service:
      app:
        controller: adguard
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          external-dns.alpha.kubernetes.io/target: external.samcloud.online
          external-dns.home.arpa/enabled: "true"
          auth.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: shield-check
          hajimari.io/group: Network
          hajimari.io/appName: adguard
          hajimari.io/name: AdGuard Home
          hajimari.io/description: "AdGuard Home is a network-wide ad blocker and DNS server."


        ports:
          http:
            primary: true
            port: 3000
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP

    persistence:
      data:
        enabled: true
        existingClaim: adguard-pvc
        globalMounts:
          - path: /opt/adguardhome/work
      conf:
        enabled: true
        existingClaim: adguard-config-pvc
        globalMounts:
          - path: /opt/adguardhome/conf
      tls:
        type: secret
        name: adguard-home-production-tls
        globalMounts:
          - path: /etc/doh

    ingress:
      app:
        className: external
        enabled: true
        annotations:
          external-dns.home.arpa/enabled: "true"
          auth.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: shield-check
          hajimari.io/group: Network
          hajimari.io/appName: adguard
        hosts:
          - host: &host "adguard.samcloud.online"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            
