---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-pvc
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 15Gi
  storageClassName: openebs-hostpath