---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.3.1
    env:
      TZ: ${TIMEZONE:=Etc/UTC}
    hajimari:
      defaultEnable: true
      lightTheme: gazette
      darkTheme: blackboard
      namespaceSelector:
        matchNames:
          - default
          - openebs
          - media
          - network
          - kube-system
          - observability
          - flux-system
          - external
      name: "Sam"
      defaultSearchProvider: Kagi
      searchProviders:
        - name: Kagi
          token: "y"
          icon: simple-icons:kagi
          searchUrl: https://kagi.com/search?q={query}
          url: https://kagi.com
      globalBookmarks:
        - group: Admin
          bookmarks:
            - name: Midjourney
              url: "https://www.midjourney.com/app/"
            - name: Unifi
              url: "https://unifi.ui.com/consoles"
            - name: "Cloudflare dashboard"
              url: "https://dash.cloudflare.com/"
        - group: Daily
          bookmarks:
            - name: k8s-at-home-search
              url: "https://kubesearch.dev/"
            - name: "Selfhosted newsletter"
              url: "https://selfh.st"
            - name: Artifacthub
              url: "https://artifacthub.io/"
            - name: "Loki logs"
              url: "https://grafana.samcloud.online/explore"
            - name: InfoSecNews
              url: "https://allinfosecnews.com"
            - name: "News"
              url: "https://www.newsminimalist.com/"
        - group: DevOps
          bookmarks:
            - name: HomeLab
              url: "https://github.com/samuelbartels20/kubernetes-homelab"

            - name: TerraformCloud
              url: "https://app.terraform.io/"
            - name: Visual studio
              url: https://my.visualstudio.com"
            - name: Atlantis
              url: "https://www.runatlantis.io/"
            - name: Git-cleaner
              url: "https://rtyley.github.io/bfg-repo-cleaner/"
            - name: K8S Exam simulator
              url: "https://killer.sh/"
            - name: Github-download-folder
              url: "https://download-directory.github.io"
        - group: Fun
          bookmarks:
            - name: Translator
              url: "https://www.deepl.com/translator"
            - name: Archive
              url: "https://archive.ph"
            - name: Wallpapers
              url: "https://unsplash.com"
            - name: "Anime"
              url: "https://anichart.net/"
            - name: Diving-sites
              url: "https://www.padi.com/dive-sites"
        - group: Reddit
          bookmarks:
            - name: "/r/midjourney"
              url: "https://red.artemislena.eu/r/midjourney"
            - name: "/r/selfhosted"
              url: "https://red.artemislena.eu/r/selfhosted/"
            - name: "/r/kubernetes"
              url: "https://red.artemislena.eu/r/kubernetes/"
            - name: "/r/virtualreality"
              url: "https://red.artemislena.eu/r/virtualreality/"
            - name: "/r/mk"
              url: "https://red.artemislena.eu/r/mechanicalkeyboards/"
            - name: "/r/ChatGPT"
              url: "https://red.artemislena.eu/r/ChatGPT/"
            - name: "/r/plex"
              url: "https://red.artemislena.eu/r/plex/"
            - name: "/r/NonCredibleDefense"
              url: "https://red.artemislena.eu/r/NonCredibleDefense/"
        - group: Tech
          bookmarks:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
            - name: Shodan
              url: "https://shodan.io"
            - name: Intelx
              url: "https://intelx.io/"
            - name: Greynoise
              url: "https://www.greynoise.io/"
            - name: GrayHatWarFare
              url: "https://www.greyhatwarfare.com/"
            - name: GPP Tools
              url: "https://bgp.tools"
            - name: BGP View
              url: "https://bgpview.io"
            - name: "Bookhatrix"
              url: "https://book.hacktricks.xyz"
            - name: "Pentest-tools"
              url: "https://offsec.tools/"
        -         - group: Communicate
          bookmarks:
            - name: Discord
              url: 'https://discord.com'
            - name: Gmail
              url: 'http://gmail.com'
            - name: Slack
              url: 'https://slack.com/signin'
        - group: Cloud
          bookmarks:
            - name: Box
              url: 'https://box.com'
            - name: Dropbox
              url: 'https://dropbox.com'
            - name: Drive
              url: 'https://drive.google.com'
        - group: Design
          bookmarks:
            - name: Awwwards
              url: 'https://awwwards.com'
            - name: Dribbble
              url: 'https://dribbble.com'
            - name: Muz.li
              url: 'https://medium.muz.li/'
        - group: Dev
          bookmarks:
            - name: Codepen
              url: 'https://codepen.io/'
            - name: Devdocs
              url: 'https://devdocs.io'
            - name: Devhints
              url: 'https://devhints.io'
        - group: Lifestyle
          bookmarks:
            - name: Design Milk
              url: 'https://design-milk.com/category/interior-design/'
            - name: Dwell
              url: 'https://www.dwell.com/'
            - name: Freshome
              url: 'https://www.mymove.com/freshome/'
        - group: Media
          bookmarks:
            - name: Spotify
              url: 'http://browse.spotify.com'
            - name: Trakt
              url: 'http://trakt.tv'
            - name: YouTube
              url: 'https://youtube.com/feed/subscriptions'
        - group: Reading
          bookmarks:
            - name: Instapaper
              url: 'https://www.instapaper.com/u'
            - name: Medium
              url: 'http://medium.com'
            - name: Reddit
              url: 'http://reddit.com'
        - group: Tech
          bookmarks:
            - name: TheNextWeb
              url: 'https://thenextweb.com/'
            - name: The Verge
              url: 'https://theverge.com/'
            - name: MIT Technology Review
              url: 'https://www.technologyreview.com/'
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          gatus.io/enabled: "true"
          external-dns.home.arpa/enabled: "true"
          auth.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/group: "Web"
          hajimari.io/appName: "Hajimari"
          external-dns.alpha.kubernetes.io/target: "external.samcloud.online"
          external-dns.alpha.kubernetes.io/hostname: "home.samcloud.online"

          hajimari.io/icon: "weather-sunset"
        hosts:
          # - host: &custom-host "home.samcloud.online"
          #   paths:
          #     - path: /
          #       pathType: Prefix
          - host:   &host "{{ .Release.Name }}.samcloud.online"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *custom-host
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-pvc
    podSecurityContext:
      fsGroup: 101
    podAnnotations:
      configmap.reloader.stakater.com/reload: "hajimari-settings"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
