---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: excalidraw
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  suspend: false
  # dependsOn:
  #   - name: ingress-nginx-external
  #   - name: onepassword

  path: ./kubernetes/apps/default/excalidraw/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: excalidraw
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
