---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blocky
  labels:
    substitution.flux/enabled: true
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  path: "./kubernetes/apps/network/blocky/app"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  postBuild:
    substitute:
      APP: blocky
      CAPACITY: 5Gi
      GATUS_PATH: /System/Ping
  commonMetadata:
    labels:
      app.kubernetes.io/name: blocky
  dependsOn:
    - name: dragonfly-cluster
      namespace: database
    - name: onepassword
      namespace: external-secrets

