---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
components:
  - ../../components/common
resources:
  - ./uptime-kuma/ks.yaml
#  - ./gatus/ks.yaml
  - ./blackbox-exporter/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
