---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
spec:
  interval: 15m
  chart:
    spec:
      interval: 15m
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/filebrowser/filebrowser
              tag: v2.31.2@sha256:a4da9ca8364b0a1fc5dd36f7add92582bf673c0ae0bda8dd9bd13062c41d1715
            env:
              FB_DATABASE: /config/filebrowser.db
              FB_LOG: stdout
              FB_NOAUTH: true
              FB_ROOT: /data
              TZ: UTC
              FILEBROWSER_CONFIG_DIR: &datadir /config
            resources:
              requests:
                cpu: 15m
                memory: 411M
              limits:
                memory: 411M
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    ingress:
      main:
        className: external
        annotations:
          external-dns.home.arpa/enabled: "true"
          auth.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/group: "Tools"
          hajimari.io/icon: "filebrowser"
          hajimari.io/name: "File Browser"
          external-dns.alpha.kubernetes.io/target: external.samcloud.online
        hosts:
          - host: &host "fb.samcloud.online"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: filebrowser
        globalMounts:
          - path: *datadir
