apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      stirling-pdf:
        type: deployment
        replicas: 1
        containers:
          main:
            image:
              repository: ghcr.io/stirling-tools/stirling-pdf
              tag: 0.46.2@sha256:396ca949b81198a65b9abfec38518fa44e871b1970dad9f9718ffd030eef9b92
            env:
              TZ: UTC
              DOCKER_ENABLE_SECURITY: false
              LANGS: en_US
              METRICS_ENABLED: false
              SYSTEM_DEFAULTLOCALE: en-US
              SYSTEM_ENABLEANALYTICS: false
              SECURITY_ENABLE_LOGIN: false
              SYSTEM_GOOGLEVISIBILITY: false
              SYSTEM_SHOW_UPDATE: false
              STIRLINGPDF_DATA_DIR: /data
              TMPDIR: /tmp/stirling
              TEMP: /tmp/stirling
              TMP: /tmp/stirling
            securityContext:
              readOnlyRootFilesystem: false
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            volumeMounts:
              - name: data
                mountPath: /data
              - name: temp
                mountPath: /tmp/stirling
            resources:
              requests:
                cpu: "10m"
                memory: "512Mi"
              limits:
                cpu: "1"
                memory: 2Gi
        initContainers:
          - name: init-tempdir
            image: busybox
            command: ['sh', '-c', 'mkdir -p /tmp/stirling && chmod 777 /tmp/stirling']
            volumeMounts:
              - name: temp
                mountPath: /tmp/stirling
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: stirlingpdf-pvc
          - name: temp
            emptyDir: {}

    persistence:
      enabled: false  # Disable the default persistence as we're managing it manually

    service:
      stirling-pdf:
        controller: stirling-pdf
        ports:
          http:
            port: 8080

    ingress:
      main:
        className: external
        annotations:
          external-dns.home.arpa/enabled: "true"
          auth.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/group: "Tools"
          hajimari.io/icon: "mdi:file-pdf-box"
          external-dns.alpha.kubernetes.io/target: external.samcloud.online
        hosts:
          - host: "pdf.samcloud.online"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: stirling-pdf
                  port: http
        tls:
          - hosts:
              - "pdf.samcloud.online"
            secretName: pdf-production-tls
