apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      stirling-pdf:
        type: deployment
        replicas: 1
        securityContext:
          fsGroup: 1000  # Ensure proper permissions for mounted volumes
        containers:
          main:
            image:
              repository: ghcr.io/stirling-tools/stirling-pdf
              tag: 0.46.2@sha256:396ca949b81198a65b9abfec38518fa44e871b1970dad9f9718ffd030eef9b92
            env:
              TZ: UTC
              DOCKER_ENABLE_SECURITY: "false"  # Disable security features requiring system writes
              LANGS: "eng"  # Only English to minimize tessdata requirements
              METRICS_ENABLED: "false"
              SYSTEM_DEFAULTLOCALE: en-US
              SYSTEM_ENABLEANALYTICS: "false"
              SECURITY_ENABLE_LOGIN: "false"
              SYSTEM_GOOGLEVISIBILITY: "false"
              SYSTEM_SHOW_UPDATE: "false"
              STIRLINGPDF_DATA_DIR: /data
              TESSDATA_PREFIX: /data/tessdata  # Custom tessdata location
              TMPDIR: /tmp/stirling  # Custom temp directory
              TEMP: /tmp/stirling
              TMP: /tmp/stirling
              HOME: /data/home  # Custom home directory
            securityContext:
              readOnlyRootFilesystem: false  # Temporarily set to false for initialization
              runAsUser: 1000
              runAsGroup: 1000
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            volumeMounts:
              - name: data
                mountPath: /data
              - name: temp
                mountPath: /tmp/stirling
              - name: fonts
                mountPath: /usr/share/fonts
              - name: scripts
                mountPath: /scripts
              - name: configs
                mountPath: /configs
              - name: pipeline
                mountPath: /pipeline
              - name: custom-files
                mountPath: /customFiles
            resources:
              requests:
                cpu: "10m"
                memory: "512Mi"
              limits:
                cpu: "1"
                memory: "2Gi"
            lifecycle:
              postStart:
                exec:
                  command: ["sh", "-c", "chmod -R 777 /tmp/stirling && chown -R 1000:1000 /data"]

        initContainers:
          - name: setup-directories
            image: busybox
            command:
              - sh
              - -c
              - |
                mkdir -p /data/tessdata
                mkdir -p /data/home
                mkdir -p /data/logs
                mkdir -p /data/fonts
                wget -O /data/tessdata/eng.traineddata https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata
                chown -R 1000:1000 /data
            volumeMounts:
              - name: data
                mountPath: /data

        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: stirlingpdf-pvc
          - name: temp
            emptyDir: {}
          - name: fonts
            emptyDir: {}
          - name: scripts
            emptyDir: {}
          - name: configs
            emptyDir: {}
          - name: pipeline
            emptyDir: {}
          - name: custom-files
            emptyDir: {}

    persistence:
      enabled: false  # Disable default persistence as we're managing it manually

    service:
      stirling-pdf:
        controller: stirling-pdf
        ports:
          http:
            port: 8080

    ingress:
      main:
        className: external
        annotations:
          external-dns.home.arpa/enabled: "true"
          auth.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/group: "Tools"
          hajimari.io/icon: "mdi:file-pdf-box"
          external-dns.alpha.kubernetes.io/target: external.samcloud.online
        hosts:
          - host: "pdf.samcloud.online"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: stirling-pdf
                  port: http
        tls:
          - hosts:
              - "pdf.samcloud.online"
            secretName: pdf-production-tls
