---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app excalidraw
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
    image:
      # https://github.com/excalidraw/excalidraw/pull/6143
      repository: excalidraw/excalidraw
      tag: latest@sha256:b9973321c3be422bed33d36f684155039daf4ef760f42fcb49d92c58a935e4bd
      pullPolicy: IfNotPresent
    env:
      FILEBROWSER_CONFIG_DIR: &datadir /config
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: external
        annotations:
          #external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/group: "Public"
          hajimari.io/enable: "true"
          external-dns.home.arpa/enabled: "true"
          hajimari.io/icon: mdi:draw-pen
          hajimari.io/name: "Excalidraw"
          auth.home.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/hostname: "draw.samcloud.online"
        hosts:
          - host: &host "draw.samcloud.online"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: *app
    resources:
      requests:
        cpu: 5m
        memory: 10Mi
      limits:
        memory: 50Mi
    persistence:
      config:
        enabled: true
        existingClaim: excalidraw-pvc
        globalMounts:
          - path: *datadir
