---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: excalidraw-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
