---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  path: ./kubernetes/apps/observability/grafana/app
  prune: true
  dependsOn:
    - name: onepassword
      namespace: external-secrets
    - name: kube-prometheus-stack
      namespace: observability
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
