# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: gatus-secret
stringData:
    PUSHOVER_TOKEN: ENC[AES256_GCM,data:jCpHiOPq84C0L5v3Fu3cxFxJZoMxAcp2v7RSXiI5,iv:gnVQQ4dlF+wduLWzB1uy10YqNY6UUt97O6W8XvJdmac=,tag:QpeznMUxGaMWaGxOSDKLaw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:TjqwHyM=,iv:52ThSVUpIK2ZgY5Rx+hw/SzqMv+r5idSY3PQ27C30x4=,tag:geZLbo9qiNvaFvea49CacQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Q5IxNY34G8Mtn1bEE9ZX8yyeDix1/iWpEVmA0sAN9+c=,iv:FDR53laFjr4iGKaVLGqLKGydBMAPw9L8COpTzzcuNjE=,tag:Wez2+expCxlKvlEvtUi9pQ==,type:str]
