apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:wP4T77TO7jKFEHXZtFEs,iv:i35ojPMK5Vc6ZHb/UkzQha8oPZWukpTPe/8sH1bH/Wg=,tag:8ZVsiYNE04moOU+Ay7e+eg==,type:str]
sops:
  age:
    - recipient: age1ttpdjs0hthl58l4sc4n4dufuchumvlpj7zra0w48mpccf96ax3mqtap3ae
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZnZKM1hHck9nYi9WcVZp
        MWdIa0lseVQ3em94V1NxU3MwM3RGSVNLWHpNCjM5WXQ1SklDblRqSzQzdXllaElI
        eG0wcWRuNGtDSjRKTktjZDNvVS9xU2cKLS0tIEhZU1hpVUxzWXlpVnpHaGdBSDFm
        RHJBdGhia1hxRE1ncUxuL051QURFSVEK+RS6INr8glvJx1PoMfLiGRyPWK05Q5yC
        b12RaPS2dTgPhTFgOjuvaCsnl2YDghknxW8R3Q2ctPNI0MF5ddevVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-13T03:00:58Z"
  mac: ENC[AES256_GCM,data:mOrSOUvriQMekXZJn9OlkzN+5S1eELajK12LXA5Tg0fn5NK6JGP9vQZGcPU7dys/w2Y1B6+ZIRV29SklE+axWiZI6VL8Ica3qZLsoMvsyOJZ0LCgfE9N495Z2kcFGREJw7RBk1H6YXqp635MsKEXvYQE0D9VXvbOAOYalLZJNJk=,iv:FkLqvfcyLswKdHmfoesFZukLqWxVvayYL6O3Hj8vtVg=,tag:MB6Ylk49qC85iqlacED6Yg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
