apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: openebs
      namespace: openebs-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      alertmanager:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        statefulset:
          volumeClaimTemplates:
            - name: alertmanager
              accessMode: ReadWriteOnce
              size: 50Mi
              storageClass: openebs-hostpath
              globalMounts:
                - path: /alertmanager
        containers:
          alertmanager:
            image:
              repository: quay.io/prometheus/alertmanager
              tag: v0.28.1
            ports:
              - name: http
                containerPort: 9093
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 11m
                memory: 50M
              limits:
                memory: 99M

    service:
      app:
        controller: alertmanager
        ports:
          http:
            port: 9093

    persistence:
      config:
        type: configMap
        name: alertmanager
        globalMounts:
          - path: /etc/alertmanager
      secrets:
        type: secret
        name: alertmanager-secret
        globalMounts:
          - path: /etc/secrets

    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        gethomepage.dev/enabled: "true"
        gethomepage.dev/icon: alertmanager.png
        gethomepage.dev/name: Alertmanager
        gethomepage.dev/group: Monitoring
        external-dns.alpha.kubernetes.io/target: "external.samcloud.online"
        external-dns.alpha.kubernetes.io/hostname: "alertmanager.samcloud.online"
        hajimari.io/enable: "true"
        hajimari.io/group: "Monitoring"
        hajimari.io/icon: "mdi:bell"
      hosts:
        - host: "alertmanager.samcloud.online"
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: alertmanager
                  port:
                    number: 9093
      tls:
        - hosts:
            - "alertmanager.samcloud.online"
