---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app alertmanager
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: openebs
      namespace: openebs-system
  values:
    controllers:
      alertmanager:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: storage
              accessMode: ReadWriteOnce
              size: 50Mi
              storageClass: openebs-hostpath

              globalMounts:
                - path: /alertmanager

        containers:
          app:
            image:
              repository: quay.io/prometheus/alertmanager
              tag: v0.28.1
            ports:
              - name: http
                containerPort: 9093
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 11m
                memory: 50M
              limits:
                memory: 99M

    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 9093

    route:
      app:
        hostnames: ["{{ .Release.Name }}.samcloud.online"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        type: configMap
        name: alertmanager-configmap
        globalMounts:
          - path: /etc/alertmanager
      secrets:
        type: secret
        name: alertmanager-secret
        globalMounts:
          - path: /etc/secrets
