route:
  app:
    hostnames:
      - alertmanager.samcloud.online
    parentRefs:
      - name: external
        namespace: kube-system
        sectionName: https
    rules:
      - backendRefs:
          - name: app  # Changed from 'identifier' to 'name'
            port: *port
