---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: observability
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/managed-by: fluxcd
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: observability
    app.kubernetes.io/version: "4.0.1"
    helm.toolkit.fluxcd.io/release-name: alertmanager
    helm.toolkit.fluxcd.io/release-namespace: observability
    helm.toolkit.fluxcd.io/chart: app-template
    helm.toolkit.fluxcd.io/chart-version: "4.0.1"
    helm.toolkit.fluxcd.io/managed-by: fluxcd
    helm.toolkit.fluxcd.io/auto-rollback: "true"
    helm.toolkit.fluxcd.io/auto-upgrade: "true"
    helm.toolkit.fluxcd.io/auto-uninstall: "true"
    helm.toolkit.fluxcd.io/auto-install: "true"
    helm.toolkit.fluxcd.io/auto-values: "true"
    helm.toolkit.fluxcd.io/auto-annotations: "true"
    helm.toolkit.fluxcd.io/auto-labels: "true"
    helm.toolkit.fluxcd.io/auto-namespace: "true"
    helm.toolkit.fluxcd.io/auto-dependencies: "true"
    helm.toolkit.fluxcd.io/auto-interval: "30m"
    helm.toolkit.fluxcd.io/auto-max-history: "2"
    helm.toolkit.fluxcd.io/auto-retries: "3"
    helm.toolkit.fluxcd.io/auto-cleanup-on-fail: "true"
    helm.toolkit.fluxcd.io/auto-create-namespace: "true"
    helm.toolkit.fluxcd.io/auto-remediation: "true"
    helm.toolkit.fluxcd.io/auto-keep-history: "false"
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: openebs
      namespace: openebs-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  maxHistory: 2
  values:
    controllers:
      alertmanager:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: alertmanager
              accessMode: ReadWriteOnce
              size: 50Mi
              storageClass: openebs-hostpath
              globalMounts:
                - path: /alertmanager

        containers:
          alertmanager:
            image:
              repository: quay.io/prometheus/alertmanager
              tag: v0.28.1
            ports:
              - name: http
                containerPort: 9093
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 11m
                memory: 50M
              limits:
                memory: 99M

    service:
      app:
        controller: alertmanager
        ports:
          http:
            port: &port 9093

    persistence:
      config:
        type: configMap
        name: alertmanager
        globalMounts:
          - path: /etc/alertmanager
      secrets:
        type: secret
        name: alertmanager-secret
        globalMounts:
          - path: /etc/secrets

    route:
      app:
        hostnames:
          - alertmanager.samcloud.online
        annotations:
          external-dns.home.arpa/enabled: "true"
          auth.home.arpa/enabled: "true"
          hajimari.io/enable: "true"
          hajimari.io/group: "Monitoring"
          hajimari.io/icon: "mdi:bell"
          external-dns.alpha.kubernetes.io/target: external.samcloud.online
          external-dns.alpha.kubernetes.io/hostname: alertmanager.samcloud.online
        parentRefs:
          - name: external
            kind: IngressClass
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
