---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app blackbox-exporter
  namespace: &namespace monitoring
  labels:
    substitution.flux.home.arpa/enabled: "true"
    app.kubernetes.io/instance: *app
    app.kubernetes.io/managed-by: flux-system
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: v0.20.0
    app.kubernetes.io/created-by: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/monitoring/blackbox-exporter/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: *namespace
  timeout: 5m
  wait: false
