---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pihole
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/network/pihole/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      name: pihole
      namespace: network
    - apiVersion: v1
      kind: Endpoints
      name: pihole
      namespace: network
    - apiVersion: v1
      kind: Service
      name: pihole
      namespace: network
  interval: 30m
  retryInterval: 1m
  timeout: 3m
