---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  - ./uptime-kuma/ks.yaml
  - ./gatus/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./grafana/ks.yaml
  # - ./loki/ks.yaml
  # - ./alloy/ks.yaml
  # - ./alertmanager/ks.yaml

