---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: democratic-csi
  namespace: flux-system
spec:
  type: oci
  interval: 12h
  url: oci://ghcr.io/democratic-csi/charts/democratic-csi
