---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pgadmin-secret
    creationPolicy: Owner
    template:
      data:
        PGADMIN_DEFAULT_EMAIL: "${SECRET_EMAIL}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .PGADMIN_PASSWORD }}"
        pgpass: |
          192.168.8.101:5432:postgres:postgres:"{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
  - extract:
      key: pgadmin-secret
      property: PGADMIN_PASSWORD
  - extract:
      key: cloudnative-pg
      property: POSTGRES_SUPER_PASS 
  # data:
  #   - secretKey: PGADMIN_PASSWORD
  #     remoteRef:
  #       key: &key 3db30322-7dbb-4659-a8ab-8764d0f320f2
  #       property: PGADMIN_PASSWORD
  #   - secretKey: POSTGRES_SUPER_PASS
  #     remoteRef:
  #       key: *key
  #       property: POSTGRES_SUPER_PASS
