
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      # renovate: registryUrl=https://kubernetes.github.io/dashboard
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: cloudnative-pg
      namespace: database
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: dpage/pgadmin4
              tag: "9.3@sha256:bd71932cb1ef94719e783f0eed42c227bc67877a7c7e076c7092738711e5f4d4"
            env:
              PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
              PGADMIN_DISABLE_POSTFIX: "true"
              PGADMIN_LISTEN_PORT: &port 80
              PGADMIN_DEFAULT_EMAIL:
                valueFrom:
                  secretKeyRef:
                    name: pgadmin-secret
                    key: PGADMIN_DEFAULT_EMAIL
              PGADMIN_DEFAULT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: pgadmin-secret
                    key: PGADMIN_DEFAULT_PASSWORD
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 500Mi
    service:
      main:
        controller: main
    ingress:
      main:
        enabled: true
        className: external
        ingressClassName: external
        annotations:
          external-dns.home.arpa/enabled: "true"
          auth.home.arpa/enabled: "false"
          hajimari.io/enable: "true"
          hajimari.io/icon: "simple-icons:postgresql"
          hajimari.io/group: "Database"
          hajimari.io/appNname: "Kubernetes Dashboard"
          external-dns.alpha.kubernetes.io/target: external.samcloud.online
        hosts:
          - host: &host "{{ .Release.Name }}.samcloud.online"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: pgadmin-production-tls
    metricsScraper:
      enabled: true
    cert-manager:
      enabled: false
    nginx:
      enabled: false
    extras:
      serviceMonitor:
        enabled: true
    persistence:
      config:
        enabled: true
        existingClaim: pgadmin-pvc
        globalMounts:
          - subPath: pgadmin
            path: /var/lib/pgadmin
    podSecurityContext:
      runAsUser: ${PUID}
      runAsGroup: ${PGID}
