---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashboard
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 12h
  values:
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        ingressClassName: external
        useDefaultIngressClass: false
        annotations:
          external-dns.home.arpa/enabled: "true"
          auth.home.arpa/enabled: "false"
          hajimari.io/enable: "true"
          hajimari.io/appNname: "Kubernetes Dashboard"
          hajimari.io/group: "System"
          hajimari.io/icon: mdi:kubernetes
          external-dns.alpha.kubernetes.io/target: external.samcloud.online
        hosts:
          - host: &host pgadmin.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: kubernetes-dashboard-production-tls
    metricsScraper:
      enabled: true
    cert-manager:
      enabled: false
    nginx:
      enabled: false
    extras:
      serviceMonitor:
        enabled: true
    persistence:
      config:
        enabled: true
        existingClaim: kubernetes-dashboard-pvc
        globalMounts:
          - subPath: dashboard
            path: /var/lib/kubernetes-dashboard
    podSecurityContext:
      runAsUser: ${PUID}
      runAsGroup: ${PGID}
      fsGroup: ${PGID}
      fsGroupChangePolicy: "OnRootMismatch"
