---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: truenas
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: truenas-secrets
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .username }}"
        name: "{{ .name }}"
        SECRET_NAS_API_KEY: "{{ .SECRET_NAS_API_KEY }}"

  dataFrom:
    - extract:
        key: cloudnative-pg
